# Generated by Django 6.0.1 on 2026-02-24 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StreamingApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producer',
            name='producer_url',
        ),
        migrations.RemoveField(
            model_name='studio',
            name='studio_url',
        ),
    ]
