# Generated by Django 6.0.1 on 2026-02-24 01:29

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StreamingApp', '0002_remove_producer_producer_url_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='producer',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_producer_name_case_insensitive'),
        ),
        migrations.AddConstraint(
            model_name='studio',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('studio_name'), name='unique_studio_name_case_insensitive'),
        ),
    ]
