# Generated by Django 6.0.2 on 2026-02-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StreamingApp', '0003_producer_unique_producer_name_case_insensitive_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='producer',
        ),
        migrations.RemoveField(
            model_name='series',
            name='studio',
        ),
        migrations.AddField(
            model_name='series',
            name='producer',
            field=models.ManyToManyField(to='StreamingApp.producer'),
        ),
        migrations.AddField(
            model_name='series',
            name='studio',
            field=models.ManyToManyField(to='StreamingApp.studio'),
        ),
    ]
