# Generated by Django 6.0.2 on 2026-02-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StreamingApp', '0004_remove_series_producer_remove_series_studio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='genre',
            field=models.ManyToManyField(through='StreamingApp.SeriesGenre', to='StreamingApp.genre'),
        ),
        migrations.AddField(
            model_name='series',
            name='thumbnail_picture',
            field=models.ImageField(blank=True, null=True, upload_to='series_thumbnails/'),
        ),
    ]
