# Generated by Django 6.0.2 on 2026-02-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StreamingApp', '0005_series_genre_series_thumbnail_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='score',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='series',
            name='rating',
            field=models.CharField(choices=[('g', 'G - All Ages'), ('pg', 'PG - Children'), ('pg_13', 'PG-13 - Teens 13 or older'), ('r', 'R - 17+ (violence & profanity)')], max_length=10),
        ),
    ]
