# Generated by Django 6.0.2 on 2026-02-27 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StreamingApp', '0007_alter_genre_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
