# Generated by Django 6.0.2 on 2026-02-27 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StreamingApp', '0008_alter_series_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='duration_seconds',
        ),
    ]
