# Generated by Django 6.0.2 on 2026-02-27 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StreamingApp', '0009_remove_episode_duration_seconds'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='title',
            new_name='episode_title',
        ),
    ]
