# Generated by Django 6.0.1 on 2026-03-07 03:07

import core.StreamingApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StreamingApp', '0010_rename_title_episode_episode_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture_url',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/', validators=[core.StreamingApp.models.validate_image_size]),
        ),
    ]
