# Generated by Django 6.0.1 on 2026-03-07 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StreamingApp', '0011_alter_user_profile_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchhistory',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='StreamingApp.series'),
        ),
    ]
