# Generated by Django 6.0.1 on 2026-03-09 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StreamingApp', '0012_watchhistory_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='is_published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
