# Generated by Django 6.0.1 on 2026-03-10 01:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StreamingApp', '0013_series_is_published_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotLightSeries',
            fields=[
                ('spotlight_series_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StreamingApp.series')),
            ],
            options={
                'unique_together': {('series',)},
            },
        ),
    ]
