# Generated by Django 6.0.1 on 2026-03-10 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StreamingApp', '0014_spotlightseries'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotlightseries',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='spotlight_series_images/'),
        ),
    ]
