# Generated by Django 6.0.1 on 2026-03-11 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StreamingApp', '0015_spotlightseries_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='StreamingApp.series'),
        ),
    ]
